[package]
name = "data-eater-services"
edition = "2021"
version.workspace = true
description.workspace = true
readme.workspace = true
license-file.workspace = true
authors.workspace = true
categories.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
